# Generated by Django 4.2 on 2023-10-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgustin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='imagen',
            field=models.CharField(default='https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col/image.png', max_length=300),
        ),
    ]
