# Generated by Django 4.2 on 2023-10-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAgustin', '0002_pilotos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotos',
            name='imagen_bandera',
            field=models.CharField(default='https://media.formula1.com/content/dam/fom-website/flags/Netherlands.gif', max_length=300),
        ),
    ]
